/**
 * Centralized registry of application telemetry and event names.
 * Ensures consistent naming, prevents duplication, and provides type-safe autocompletion.
 */
export const TelemetryEvents = {
  // --- HTTP & Network Telemetry ---
  HTTP_REQUEST_START: 'HTTP_REQUEST_START',
  HTTP_REQUEST_SUCCESS: 'HTTP_REQUEST_SUCCESS',
  HTTP_REQUEST_ERROR: 'HTTP_REQUEST_ERROR',
  httpStart: (method: string): string => `HTTP_${method.toUpperCase()}_START`,
  httpSuccess: (method: string): string => `HTTP_${method.toUpperCase()}_SUCCESS`,
  httpError: (method: string): string => `HTTP_${method.toUpperCase()}_ERROR`,

  // --- Orders Domain Events ---
  ORDERS_LOADED: 'ORDERS_LOADED',
  ORDERS_STATE_UPDATED: 'ORDERS_STATE_UPDATED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  NEW_ORDER_BUTTON_CLICKED: 'NEW_ORDER_BUTTON_CLICKED',
  ORDER_ROW_CLICKED: 'ORDER_ROW_CLICKED',
  ORDER_FILTER_CLICKED: 'ORDER_FILTER_CLICKED',

  // --- Support & Tickets Feature ---
  TICKETS_LOADED: 'TICKETS_LOADED',
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_ROW_CLICKED: 'TICKET_ROW_CLICKED',
  NEW_TICKET_BUTTON_CLICKED: 'NEW_TICKET_BUTTON_CLICKED',

  // --- AI Chat Assistant Feature ---
  AI_MODEL_MENU_OPEN: 'AI_MODEL_MENU_OPEN',
  AI_MODEL_SELECT: 'AI_MODEL_SELECT',
  AI_MODEL_CHANGED: 'AI_MODEL_CHANGED',
  AI_NEW_CHAT_CLICK: 'AI_NEW_CHAT_CLICK',
  AI_EXPORT_CHAT_CLICK: 'AI_EXPORT_CHAT_CLICK',
  AI_QUICK_PROMPT_CLICK: 'AI_QUICK_PROMPT_CLICK',
  AI_VIEW_ORDER_CLICK: 'AI_VIEW_ORDER_CLICK',
  AI_OPEN_SUPPORT_CLICK: 'AI_OPEN_SUPPORT_CLICK',
  AI_COPY_MESSAGE_CLICK: 'AI_COPY_MESSAGE_CLICK',
  AI_REGENERATE_CLICK: 'AI_REGENERATE_CLICK',
  AI_CHIP_TRACK_CLICK: 'AI_CHIP_TRACK_CLICK',
  AI_CHIP_RETURN_CLICK: 'AI_CHIP_RETURN_CLICK',
  AI_CHIP_SPEND_CLICK: 'AI_CHIP_SPEND_CLICK',
  AI_STOP_GENERATION_CLICK: 'AI_STOP_GENERATION_CLICK',
  AI_SEND_PROMPT_CLICK: 'AI_SEND_PROMPT_CLICK',
  AI_PROMPT_SENT: 'AI_PROMPT_SENT',
  AI_CHAT_SESSION_CREATED: 'AI_CHAT_SESSION_CREATED',
  AI_SESSION_CREATED: 'AI_SESSION_CREATED',
  AI_SESSION_DELETED: 'AI_SESSION_DELETED',
  AI_CHAT_CLEARED: 'AI_CHAT_CLEARED',
  AI_FEEDBACK_SUBMITTED: 'AI_FEEDBACK_SUBMITTED',
  AI_RESPONSE_COMPLETED: 'AI_RESPONSE_COMPLETED',
  AI_STREAM_COMPLETED: 'AI_STREAM_COMPLETED',
  AI_STREAM_FAILED: 'AI_STREAM_FAILED',

  // --- Settings & Appearance ---
  THEME_CHANGED: 'THEME_CHANGED',
  COLOR_PALETTE_CHANGED: 'COLOR_PALETTE_CHANGED',
  BASE_FONT_SIZE_CHANGED: 'BASE_FONT_SIZE_CHANGED',

  // --- Global Telemetry & System ---
  EVENTS_BUFFER_CLEARED: 'EVENTS_BUFFER_CLEARED',
  EVENTS_STREAM_TOGGLED: 'EVENTS_STREAM_TOGGLED',
} as const;

export type KnownTelemetryEvent =
  | (typeof TelemetryEvents)[Exclude<keyof typeof TelemetryEvents, 'httpStart' | 'httpSuccess' | 'httpError'>];

export type TelemetryEventName = KnownTelemetryEvent | (string & {});
